### ISSUE TITLE
由于找不到cublas64_80.dll,无法继续执行代码。重新安装程序可能会解决此问题

### ISSUE THREAD

**Issue by luckhhn** [dlunion/OpenPose#13]
在win10 下跑openpose-new.cpp,VS2015下编译通过，运行出错：由于找不到cublas64_80.dll,无法继续执行代码。重新安装程序可能会解决此问题

**Comment by luckhhn** [comment]
遇到这种问题是不是因为cuda版本的问题 ？本人是cuda9.0+cudnn9.0 。 现在知道cublas64_80.dll是装cuda8.0生成的dll。

**Comment by luckhhn** [comment]
有人帮忙回答么？

**Comment by luckhhn** [comment]
已解决

**Comment by yjsliqing** [comment]
请问是如何解决的，遇到了同样的问题

**Comment by luckhhn** [comment]
我好像是因为更新了opencv版本，貌似是这样。我隔了一段时间没有用了，期间我更新到opencv到3.4，然后也没有做别的事情了。然后再用时就可以了，我不确定是不是这个原因。当时本想写好自己是怎么解决的，但是忘记了，现在真的记不得了。抱歉哈。

**Comment by yjsliqing** [comment]
好的，多谢了




| |
yjs_liqing
邮箱：yjs_liqing@163.com
|

签名由 网易邮箱大师 定制

在2018年12月18日 18:57，luckhhn 写道：

我好像是因为更新了opencv版本，貌似是这样。我隔了一段时间没有用了，期间我更新到opencv到3.4，然后也没有做别的事情了。然后再用时就可以了，我不确定是不是这个原因。当时本想写好自己是怎么解决的，但是忘记了，现在真的记不得了。抱歉哈。
