### ISSUE TITLE
LINK错误,找不到**符号

### ISSUE THREAD

**Issue by ghost** [dlunion/OpenPose#8]
这个问题经过不断的百度,尝试,找到了答案

一般时没有引用相应的库,或者引用的库版本不对、64位还是32位不对.
第一步,添加库目库
添加方法:项目属性--vc++目录--包含目录(记住,勾选"从父级或项目默认设置继承")
第二部,添加库lib文件的名字
添加库目录:项目属性--vc++目录--库目录(记住,勾选"从父级或项目默认设置继承")
添加库的名字:项目属性--链接器--输入--附加依赖项,编辑,加入库的名字

**Comment by dlunion** [comment]
谢谢您
