### ISSUE TITLE
可以解释一下keypoints数组下标的对应关节点，和pair的意义吗

### ISSUE THREAD

**Issue by ymlei** [dlunion/OpenPose#9]
如题。谢谢！

**Comment by ymlei** [comment]
https://blog.csdn.net/u010925447/article/details/77411335
本篇为openpose_README的翻译
有以上问题的答案。（COCO模型下标对应部位）

**Comment by cuixing158** [comment]
多谢

**Comment by dlunion** [comment]
建议看这里：https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md
